### ISSUE TITLE
flet build apk isn't working 

### ISSUE THREAD

**Issue by Vasya2222** [flet-dev/flet-build-template#15]
I run the flet build apk -v v command, the same error is constant, I tried all the ways, it got to the point that I reinstalled everything. Please tell me what the error is and how to fix it.I'm going to lose my mind soon😢. The solution of the "flet build apk-vv" command is shown below.
`(myenv) PS C:\tic_tac_toe\game> flet build apk -vv
[19:58:39] Flutter executable: E:\flutter\flutter\bin\flutter.BAT
           Dart executable: E:\flutter\flutter\bin\dart.BAT
           Flutter bootstrap directory: C:\Users\vasya\AppData\Local\Temp\flet_flutter_build_0OAnTREX5p
           Additional Flutter dependencies:
           {}
[19:58:49] Created Flutter bootstrap project from gh:flet-dev/flet-build-template with ref 0.23.2 ✅
           Copying C:\tic_tac_toe\game\assets\icon.png to C:\Users\vasya\AppData\Local\Temp\flet_flutter_build_0OAnTREX5p\images
           Customized app icons and splash images ✅
           Run subprocess: ['E:\\flutter\\flutter\\bin\\dart.BAT', 'run', 'flutter_launcher_icons']
(   ●  ) Generating app icon(15.1s) 
(    ● ) Generating app icons ⏳... 
(     ●) Generating app icons ⏳...Got dependencies in `C:\Users\vasya\AppData\Local\Temp\flet_flutter_build_0OAnTREX5p`.
(  ●   ) Generating app icons ⏳... (5.6s)
Built flutter_launcher_icons:flutter_launcher_icons.
(    ● ) Generating app icons ⏳...  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

(    ● ) Generating app icons ⏳...• Creating default icons Android
(●     ) Generating app icons ⏳...• Overwriting the default Android launcher icon with a new icon
(   ●  ) Generating app icons ⏳...• Overwriting default iOS launcher icon with new icon
(  ●   ) Generating app icons ⏳...Creating Icons for Web...
(    ● ) Generating app icons ⏳...Creating Icons for Windows...
(    ● ) Generating app icons ⏳...Creating Icons for MacOS...
(●     ) Generating app icons ⏳... 
✓ Successfully generated launcher icons
[19:59:20] Generated app icons ✅
           Run subprocess: ['E:\\flutter\\flutter\\bin\\dart.BAT', 'run', 'flutter_native_splash:create']
( ●    ) Generating splash screens ⏳... 
Built flutter_native_splash:create.
(    ● ) Generating splash screens ⏳...[Android] Creating default splash images
(●     ) Generating splash screens ⏳...[Android] Creating dark mode splash images
( ●    ) Generating splash screens ⏳...[Android] Creating default android12splash images
(    ● ) Generating splash screens ⏳...[Android] Creating dark mode android12splash images
(  ●   ) Generating splash screens ⏳...[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
(   ●  ) Generating splash screens ⏳...[Android]  - android/app/src/main/res/drawable-night/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]  - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
[Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
( ●    ) Generating splash screens ⏳...[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
(   ●  ) Generating splash screens ⏳...[iOS] Creating dark mode  images
( ●    ) Generating splash screens ⏳...[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
( ●    ) Generating splash screens ⏳...[Web] Creating images
(     ●) Generating splash screens ⏳...[Web] Creating images
(     ●) Generating splash screens ⏳...[Web] Creating background images
[Web] Creating CSS
(   ●  ) Generating splash screens ⏳...[Web] Updating index.html
(  ●   ) Generating splash screens ⏳... 
✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash

[19:59:38] Generated splash screens ✅
           Run subprocess: ['E:\\flutter\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package', 'C:\\tic_tac_toe\\game',  
           '--mobile', '--platform', 'mobile', '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude', 'build', 
           '--verbose']
( ●    ) Packaging Python app(2.7s) 
Built serious_python:main.
(   ●  ) Packaging Python app ⏳...Running package command
Creating asset directory: C:\Users\vasya\AppData\Local\Temp\flet_flutter_build_0OAnTREX5p\app
Copying Python app from C:\tic_tac_toe\game to C:\Users\vasya\AppData\Local\Temp\serious_python_temp7e72f0c4
( ●    ) Packaging Python app ⏳...Configured mobile platform with sitecustomize.py at C:\Users\vasya\AppData\Local\Temp\serious_pythoecustomized1d4f5cc\sitecustomize.py
Installing dependencies [flet-embed] with pip command to C:\Users\vasya\AppData\Local\Temp\serious_python_temp7e72f0c4\__pypackages__
Extracting Python distributive from C:\Users\vasya\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_onr.gz to C:\Users\vasya\AppData\Local\Temp\hostpython3.11_9dcfb00a
(    ● ) Packaging Python app ⏳...VERBOSE: C:\Users\vasya\AppData\Local\Temp\hostpython3.11_9dcfb00a\python\python.exe -m pip installolated --upgrade --target C:\Users\vasya\AppData\Local\Temp\serious_python_temp7e72f0c4\__pypackages__ flet-embed
(    ● ) Packaging Python app ⏳...VERBOSE: Collecting flet-embed
VERBOSE: Obtaining dependency information for flet-embed from https://files.pythonhosted.org/packages/72/f2/8716aed95d1104822d778ae9089170056a840de07687258f11f8dcb/flet_embed-0.23.2-py3-none-any.whl.metadata
VERBOSE: Using cached flet_embed-0.23.2-py3-none-any.whl.metadata (1.0 kB)
( ●    ) Packaging Python app ⏳...VERBOSE: Collecting flet-runtime==0.23.2 (from flet-embed)
VERBOSE: Obtaining dependency information for flet-runtime==0.23.2 from https://files.pythonhosted.org/packages/63/20/2c73fcacc9a64cb36bad804ae55885bdddcec972506fabfe52fca08/flet_runtime-0.23.2-py3-none-any.whl.metadata
VERBOSE: Using cached flet_runtime-0.23.2-py3-none-any.whl.metadata (1.1 kB)
(    ● ) Packaging Python app ⏳...VERBOSE: Collecting flet-core==0.23.2 (from flet-runtime==0.23.2->flet-embed)
VERBOSE: Obtaining dependency information for flet-core==0.23.2 from https://files.pythonhosted.org/packages/eb/04/71da90546ab28af7496c435341f241396aa4f6aaedb882ccff59e84/flet_core-0.23.2-py3-none-any.whl.metadata
VERBOSE: Using cached flet_core-0.23.2-py3-none-any.whl.metadata (971 bytes)
(   ●  ) Packaging Python app ⏳...VERBOSE: Collecting httpx<1,>=0 (from flet-runtime==0.23.2->flet-embed)
VERBOSE: Obtaining dependency information for httpx<1,>=0 from https://files.pythonhosted.org/packages/41/7b/ddacf6dcebb42466abd03f3682baa82e08fc0c1f8eaa05b4bae87d5/httpx-0.27.0-py3-none-any.whl.metadata
VERBOSE: Using cached httpx-0.27.0-py3-none-any.whl.metadata (7.2 kB)
( ●    ) Packaging Python app ⏳...VERBOSE: Collecting oauthlib<4.0.0,>=3.2.2 (from flet-runtime==0.23.2->flet-embed)
VERBOSE: Obtaining dependency information for oauthlib<4.0.0,>=3.2.2 from https://files.pythonhosted.org/packages/7e/80/cab10959dc1faec8384a781dfbf93cb4d33d50988f7a69f1b7c9bbe/oauthlib-3.2.2-py3-none-any.whl.metadata
VERBOSE: Using cached oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
( ●    ) Packaging Python app ⏳...VERBOSE: Collecting repath<0.10.0,>=0.9.0 (from flet-core==0.23.2->flet-runtime==0.23.2->flet-embed
VERBOSE: Obtaining dependency information for repath<0.10.0,>=0.9.0 from https://files.pythonhosted.org/packages/87/ed/92e9b8a3ffc562f4ef2538f54e911df29730e1f0d79130a4edc86e7/repath-0.9.0-py3-none-any.whl.metadata
(  ●   ) Packaging Python app ⏳... 
(   ●  ) Packaging Python app ⏳...VERBOSE: Collecting anyio (from httpx<1,>=0->flet-runtime==0.23.2->flet-embed)
VERBOSE: Obtaining dependency information for anyio from https://files.pythonhosted.org/packages/7b/a2/10639a79341f6c019dedc95bd48a492f1d1197f4c04f546fc7ae0ff/anyio-4.4.0-py3-none-any.whl.metadata
VERBOSE: Using cached anyio-4.4.0-py3-none-any.whl.metadata (4.6 kB)
(  ●   ) Packaging Python app ⏳...VERBOSE: Collecting certifi (from httpx<1,>=0->flet-runtime==0.23.2->flet-embed)
VERBOSE: Obtaining dependency information for certifi from https://files.pythonhosted.org/packages/1c/d5/c84e1a17bf61d4df64ca866a1c9a9b4e9bdc131ec689a0ad013fb36/certifi-2024.7.4-py3-none-any.whl.metadata
VERBOSE: Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
( ●    ) Packaging Python app ⏳...VERBOSE: Collecting httpcore==1.* (from httpx<1,>=0->flet-runtime==0.23.2->flet-embed)
VERBOSE: Obtaining dependency information for httpcore==1.* from https://files.pythonhosted.org/packages/78/d4/e5d7e4f2174f8a4d63c88978fe2503f7ecc03282fee1fa2719c2704/httpcore-1.0.5-py3-none-any.whl.metadata
VERBOSE: Using cached httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)
(   ●  ) Packaging Python app ⏳...VERBOSE: Collecting idna (from httpx<1,>=0->flet-runtime==0.23.2->flet-embed)
  Obtaining dependency information for idna from https://files.pythonhosted.org/packages/e5/3e/741d8c82801c347547f8a2a06aa57dbb1992be9f2ea0eda2c8b79e8/idna-3.7-py3-none-any.whl.metadata
VERBOSE: Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
(     ●) Packaging Python app ⏳...VERBOSE: Collecting sniffio (from httpx<1,>=0->flet-runtime==0.23.2->flet-embed)
  Obtaining dependency information for sniffio from https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c39abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl.metadata
VERBOSE: Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
(   ●  ) Packaging Python app ⏳...VERBOSE: Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0->flet-runtime==0.23.2->flet-em
VERBOSE: Obtaining dependency information for h11<0.15,>=0.13 from https://files.pythonhosted.org/packages/95/04/ff642e65ad6b90db43e66fb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl.metadata
VERBOSE: Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
( ●    ) Packaging Python app ⏳...VERBOSE: Collecting six>=1.9.0 (from repath<0.10.0,>=0.9.0->flet-core==0.23.2->flet-runtime==0.23.2t-embed)
VERBOSE: Obtaining dependency information for six>=1.9.0 from https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cfd792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl.metadata
VERBOSE: Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
( ●    ) Packaging Python app ⏳...VERBOSE: Using cached flet_embed-0.23.2-py3-none-any.whl (3.0 kB)
VERBOSE: Using cached flet_runtime-0.23.2-py3-none-any.whl (19 kB)
VERBOSE: Using cached flet_core-0.23.2-py3-none-any.whl (399 kB)
VERBOSE: Using cached httpx-0.27.0-py3-none-any.whl (75 kB)
VERBOSE: Using cached httpcore-1.0.5-py3-none-any.whl (77 kB)
VERBOSE: Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
VERBOSE: Using cached repath-0.9.0-py3-none-any.whl (4.7 kB)
(   ●  ) Packaging Python app ⏳...VERBOSE: Using cached anyio-4.4.0-py3-none-any.whl (86 kB)
VERBOSE: Using cached idna-3.7-py3-none-any.whl (66 kB)
VERBOSE: Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
VERBOSE: Using cached h11-0.14.0-py3-none-any.whl (58 kB)
VERBOSE: Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
(  ●   ) Packaging Python app ⏳... VERBOSE: Installing collected packages: sniffio, six, oauthlib, idna, h11, certifi, repath, httpcoVERBOSE: Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
(  ●   ) Packaging Python app ⏳... VERBOSE: Installing collected packages: snif    ● ) Packaging Python app ⏳... VERBOSE: Successfully installed anyio-4.4.0 certifi-2024.7.4 flet-core-0.23.2 flet-embed-0.23.2 flVERBOSE: Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
(  ●   ) Packaging Python app ⏳... VERBOSE: Installing collected packages: sniffio, six, oauthlib, idna, h11, certifi, repath, httpcoVERBOSE: Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)                .0AppData\Local\Temp\serious_python_temp7e72f0c4
(  ●   ) Packaging Python app ⏳... VERBOSE: Installing collected packages: sn    ● ) Packaging Python app ⏳... VERBOSE: Successfully installed anyio-4.4.0 certifi-2024.7.4 flet-core-0.23.2 flet-embed-0.23.2 flVERBOSE: Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
(  ●   ) Packaging Python app ⏳... VERBOSE: Installing collected packages: sniffio, six, oauthlib, idna, h11, certifi, repath, httpcore, anyio, http    ● ) Packaging Python app ⏳... VERBOSE: Successfully installed anyio-4.4a\AppData\Local\Temp\serious_python_temp7e72f0c4
x, flet-core, flet-runtime, flet-embed
(    ● ) Packaging Python app ⏳... VERBOSE: Successfully installed anyio-4.4.0 certifi-2024.7.4 flet-core-0.23.2 flet-embed-0.23.2 flet-runtime-0.230.14.0 httpcore-1.0.5 httpx-0.27.0 idna-3.7 oauthlib-3.2.2 repath-0.9.0 six-Temp\flet_flutter_build_0OAnTREX5p
.2 h11-0.14.0 httpcore-1.0.5 httpx-0.27.0 idna-3.7 oauthlib-3.2.2 repath-0.9.0 six-1.16.0 sniffio-1.3.1
(     ●) Packaging Python app ⏳... Compiling Python sources at C:\Users\vasya\AppData\Local\Temp\serious_python_temp7e72f0c4
VERBOSE: C:\Users\vasya\AppData\Local\Temp\hostpython3.11_9dcfb00a\python\python.exe -m compileall -b C:\Users\vasya\AppData\Local\Temp\serious_python_temp7e72f0c4
[20:00:28] Deleting Flutter bootstrap directory C:\Users\vasya\AppData\Local\Temp\flet_flutter_build_0OAnTREX5p
           Error building Flet app - see the log of failed command above.`

**Comment by FeodorFitsner** [comment]
It should be fixed in pre-release version of Flet.
